name: Unit Tests

on: 
  push:
    paths-ignore:
      - '**.md'
  pull_request:
    paths-ignore:
      - '**.md'    

jobs:

  build:
    
    strategy:
      matrix:
        os:
          - ubuntu-latest

        node:
          - '10.x'
          - '12.x'

      fail-fast: false

    name: Node ${{ matrix.node }} on ${{ matrix.os }}
    
    runs-on: ${{ matrix.os }}

    steps:

    - name: Checkout
      uses: actions/checkout@v1

    - name: Setup Node
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node }}

        
    - name: Install Playwright Dependencies
      uses: microsoft/playwright-github-action@v1

    - name: Install NPM Dependencies
      run: npm install @qooxdoo/framework --no-save --no-package-lock


    - name: Run Tests
      run: ./runtests.sh

    - name: Deploy Pages
      if: github.event_name == 'push' && github.repository == 'qooxdoo/qxl.testtapper' && github.ref == 'refs/heads/master' && matrix.node == '11.x'
      run: |
        set -x
        npx qx compile --machine-readable --target=build
        cd compiled/build
        rm -rf transpiled
        git init
        git config user.name "${GITHUB_ACTOR}"
        git config user.email "${GITHUB_ACTOR}@users.noreply.github.com"
        git add .
        git commit -m "action build"
        git push --force "https://${GITHUB_ACTOR}:${{ secrets.GITHUB_TOKEN }}@github.com/${GITHUB_REPOSITORY}.git" master:gh-pages
        rm -rf .git
        
